# Generated by Django 3.1.3 on 2020-11-18 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cowsay_app', '0002_auto_20201118_2122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='body',
            new_name='message',
        ),
    ]
